import { it, expect } from 'vitest';
import { createClient, type AuthStorage } from '../../src/index.js';
const mapping={tables:{todos:{api:'todos',primaryKey:'id',fields:{id:{type:'uuid' as const}}}}};
const now=Math.floor(Date.now()/1000),sub=Buffer.from('12345678123442348234123456789abc','hex').toString('base64url');
const encode=(v:unknown)=>Buffer.from(JSON.stringify(v)).toString('base64url');
const tokens=(tag='C',email:string|null='cached',id=sub,expired=false)=>({auth_token:`${encode({alg:'EdDSA'})}.${encode({sub:id,email,iat:now-120,exp:now+(expired?-60:600),tag})}.signature`,refresh_token:`refresh-${tag}`,csrf_token:`csrf-${tag}`});
const live=()=>({...tokens('fresh','DB-live'),refresh_token:'refresh-C'});
const defer=<T>()=>{let resolve!:(v:T)=>void;const promise=new Promise<T>(yes=>{resolve=yes;});return{resolve,promise};};
const stored=(expired=false)=>new Map([['owned',JSON.stringify({version:1,tokens:tokens('C','cached',sub,expired)})],['unrelated','keep']]);
const memory=(data:Map<string,string>):AuthStorage=>({getItem:k=>data.get(k)??null,setItem:(k,v)=>{data.set(k,v);},removeItem:k=>{data.delete(k);}});
const factory=(data:Map<string,string>,fetch:typeof globalThis.fetch,storage=memory(data))=>createClient('http://localhost:4000',undefined,{trailbase:mapping,auth:{persistSession:true,autoRefreshToken:false,storageKey:'owned',storage},global:{fetch}});
const credentials={email:'placeholder',password:'placeholder'};
it('L1-17/U17 missing cache/configuration/overload have no wire, live result only canonical id/email and genuine guarded rotation',async()=>{
  let calls=0;const empty=factory(new Map(),async()=>{calls++;throw Error('No wire');});expect((await empty.auth.getUser()).error?.name).toBe('AuthSessionMissingError');expect(calls).toBe(0);
  expect(()=>Reflect.apply(empty.auth.getUser,empty.auth,['jwt'])).toThrowError(expect.objectContaining({name:'UnsupportedFeatureError'}));
  expect(()=>createClient('http://localhost:4000',undefined,{trailbase:mapping}).auth.getUser()).toThrowError(expect.objectContaining({name:'UnsupportedFeatureError'}));
  const data=stored(),client=factory(data,async(input,init)=>{calls++;if(new URL(String(input)).pathname.endsWith('/status')){expect(init?.method).toBe('GET');expect(init?.body).toBeUndefined();expect(init?.credentials).toBe('omit');expect(init?.redirect).toBe('error');expect(Object.fromEntries(new Headers(init?.headers))).toEqual({authorization:`Bearer ${JSON.parse(data.get('owned')!).tokens.auth_token}`,'refresh-token':'refresh-C'});return Response.json(live());}expect(new Headers(init?.headers).has('refresh-token')).toBe(false);expect(new Headers(init?.headers).has('csrf-token')).toBe(false);return Response.json({records:[]});});
  const result=await client.auth.getUser();expect(result.error).toBeNull();expect(Object.keys(result.data.user!).sort()).toEqual(['email','id']);expect(result.data.user?.email).toBe('DB-live');expect(JSON.parse(data.get('owned')!).tokens).toEqual(live());result.data.user!.email='mutated';expect((await client.auth.getSession()).data.session?.user.email).toBe('DB-live');await client.auth.getUser();await client.from('todos').select();expect(calls).toBe(3);
});
it('L1-17/S04 anonymous/non200/redirect/malformed/private/identity-or-refresh mismatch never authorize cached user or clear disk',async()=>{
  for(const response of [Response.json({auth_token:null,refresh_token:null,csrf_token:null}),Response.json(live(),{status:201}),new Response('private-failure',{status:401}),Response.json({...live(),refresh_token:'different'}),Response.json({...live(),auth_token:tokens('x','DB-live',Buffer.alloc(16,7).toString('base64url')).auth_token}),Response.json({...live(),extra:1}),Response.json({...live(),csrf_token:null}),new Response('{private-prefix',{status:200}),Response.json({...live(),auth_token:`${encode({alg:'EdDSA'})}.eyJwcml2YXRl.abc`}),Response.json(tokens('C','expired',sub,true))]){
    const data=stored(),before=data.get('owned'),client=factory(data,async()=>response);const result=await client.auth.getUser();expect(result.data.user).toBeNull();expect(result.error).not.toBeNull();expect(result.error?.message).not.toContain('private');expect(data.get('owned')).toBe(before);expect((await client.auth.getSession()).data.session?.user.email).toBe('cached');
  }
  const data=stored(),before=data.get('owned');let texts=0,cancels=0,signal:AbortSignal|null|undefined;const response=new Response(new ReadableStream({cancel(){cancels++;throw Error('Cancel rejected');}}),{status:401});Object.defineProperty(response,'redirected',{value:true});response.text=async()=>{texts++;throw Error('No read');};const result=await factory(data,async(_input,init)=>{signal=init?.signal;return response;}).auth.getUser();expect(result.error?.name).toBe('AuthRedirectError');expect(texts).toBe(0);expect(cancels).toBe(1);expect(signal?.aborted).toBe(true);expect(data.get('owned')).toBe(before);
});
it('L1-17/S08 held status fetch/JSON cannot return C user after pendingB invocation same-gen commit or newer refresh rotation',async()=>{
  for(const phase of ['fetch','json','refresh'] as const){const data=stored(),held=defer<Response>(),json=defer<unknown>(),ready=defer<void>(),loginHeld=defer<Response>(),loginReady=defer<void>();const response=Response.json(live());if(phase==='json')response.json=async()=>{ready.resolve();return json.promise;};
    const client=factory(data,async input=>{const path=new URL(String(input)).pathname;if(path.endsWith('/login')){loginReady.resolve();return loginHeld.promise;}if(path.endsWith('/refresh'))return Response.json({auth_token:tokens('renewed').auth_token,csrf_token:'new-csrf'});if(phase==='json')return response;ready.resolve();return held.promise;});
    const login=phase==='refresh'?null:client.auth.signInWithPassword(credentials);if(login)await loginReady.promise;const user=client.auth.getUser();await ready.promise;if(login){loginHeld.resolve(Response.json(tokens('B')));await login;}else await client.auth.refreshSession();const before=data.get('owned');if(phase==='json')json.resolve(live());else held.resolve(response);expect((await user).error?.name).toBe('AuthStaleOperationError');expect(data.get('owned')).toBe(before);
  }
});
it('L1-17/S08 queued status rotation behind held B commit cannot install or return stale user',async()=>{
  const data=stored(),loginHeld=defer<Response>(),statusHeld=defer<Response>(),loginReady=defer<void>(),statusReady=defer<void>(),writeHeld=defer<void>(),writeReady=defer<void>();let cWrites=0;
  const client=factory(data,async input=>{if(new URL(String(input)).pathname.endsWith('/login')){loginReady.resolve();return loginHeld.promise;}statusReady.resolve();return statusHeld.promise;},{...memory(data),setItem:async(k,v)=>{if(JSON.parse(v).tokens.refresh_token==='refresh-B'){data.set(k,v);writeReady.resolve();await writeHeld.promise;}else{cWrites++;data.set(k,v);}}});
  const login=client.auth.signInWithPassword(credentials);await loginReady.promise;const user=client.auth.getUser();await statusReady.promise;loginHeld.resolve(Response.json(tokens('B')));await writeReady.promise;statusHeld.resolve(Response.json(live()));await new Promise<void>(yes=>setImmediate(yes));writeHeld.resolve();await login;expect((await user).error?.name).toBe('AuthStaleOperationError');expect(cWrites).toBe(0);expect(JSON.parse(data.get('owned')!).tokens.refresh_token).toBe('refresh-B');
});
it('L1-17/S08 held status persistence superseded by newer failed/success login compensates without stale user',async()=>{
  for(const succeeds of [true,false]){const data=stored(),before=data.get('owned'),writeHeld=defer<void>(),writeReady=defer<void>();let held=false;
    const client=factory(data,async input=>new URL(String(input)).pathname.endsWith('/status')?Response.json(live()):succeeds?Response.json(tokens('B')):new Response('Rejected',{status:401}),{...memory(data),setItem:async(k,v)=>{data.set(k,v);if(!held&&JSON.parse(v).tokens.csrf_token==='csrf-fresh'){held=true;writeReady.resolve();await writeHeld.promise;}}});
    const user=client.auth.getUser();await writeReady.promise;const login=client.auth.signInWithPassword(credentials);writeHeld.resolve();expect((await user).error?.name).toBe('AuthStaleOperationError');await login;expect(succeeds?JSON.parse(data.get('owned')!).tokens.refresh_token:data.get('owned')).toBe(succeeds?'refresh-B':before);
  }
});
it('L1-17/U17 hydration waits and expired getUser shares native refresh before live status, failed write cannot claim user',async()=>{
  const hydrating=stored(),readHeld=defer<string|null>();let wire=0;const hydration=factory(hydrating,async()=>{wire++;return Response.json(live());},{...memory(hydrating),getItem:()=>readHeld.promise});const hydratedUser=hydration.auth.getUser();await new Promise<void>(yes=>setImmediate(yes));expect(wire).toBe(0);readHeld.resolve(hydrating.get('owned')!);expect((await hydratedUser).data.user?.email).toBe('DB-live');
  const data=stored(true),held=defer<Response>(),ready=defer<void>();let refreshes=0,statuses=0;const client=factory(data,async input=>{if(new URL(String(input)).pathname.endsWith('/refresh')){refreshes++;ready.resolve();return held.promise;}statuses++;return Response.json(live());});
  const user=client.auth.getUser(),cached=client.auth.getSession();await ready.promise;held.resolve(Response.json({auth_token:tokens('renewed').auth_token,csrf_token:'new-csrf'}));expect((await user).error).toBeNull();await cached;expect(refreshes).toBe(1);expect(statuses).toBe(1);
  const disk=stored(),before=disk.get('owned');let writes=0;const failed=factory(disk,async()=>Response.json(live()),{...memory(disk),setItem:(k,v)=>{if(!writes++)throw Error('private-storage');disk.set(k,v);}});expect((await failed.auth.getUser()).error?.name).toBe('AuthStorageWriteError');expect(disk.get('owned')).toBe(before);
});
it('L1-17/P17 32 distinct canonical native identities, own required status/JWT fields and safe parser failures',async()=>{
  const ids=new Set<string>();for(let n=1;n<=32;n++){const bytes=Buffer.alloc(16);bytes.writeUInt32BE(n);bytes[6]=0x40;bytes[8]=0x80;const id=bytes.toString('base64url');ids.add(id);const original=tokens('C','cached',id),fresh={...tokens('fresh','DB-live',id),refresh_token:'refresh-C'},data=new Map([['owned',JSON.stringify({version:1,tokens:original})]]);expect((await factory(data,async()=>Response.json(fresh)).auth.getUser()).data.user?.id).toBe(`${bytes.toString('hex').slice(0,8)}-0000-4000-8000-000000000000`);}expect(ids.size).toBe(32);
  for(const key of ['auth_token','refresh_token','csrf_token','alg','sub','iat','exp']){const descriptor=Object.getOwnPropertyDescriptor(Object.prototype,key);try{const payload:Record<string,unknown>=live();let inherited:unknown=payload[key];if(['alg','sub','iat','exp'].includes(key)){const header:Record<string,unknown>={alg:'EdDSA'},claims:Record<string,unknown>={sub,email:'DB-live',iat:now-120,exp:now+600};const root=key==='alg'?header:claims;inherited=root[key];delete root[key];payload.auth_token=`${encode(header)}.${encode(claims)}.signature`;}else delete payload[key];Object.defineProperty(Object.prototype,key,{configurable:true,value:inherited});const data=stored(),before=data.get('owned');expect((await factory(data,async()=>Response.json(payload)).auth.getUser()).data.user).toBeNull();expect(data.get('owned')).toBe(before);}finally{if(descriptor)Object.defineProperty(Object.prototype,key,descriptor);else Reflect.deleteProperty(Object.prototype,key);}}
});
it('L1-17/S08 discarded successful status owns abort/cancel even rejected or held cancellation, never replaces stale result or reads body',async()=>{
  for(const hangs of [false,true]){const data=stored(),held=defer<Response>(),ready=defer<void>();let cancels=0,reads=0,signal:AbortSignal|null|undefined;
    const response=new Response(new ReadableStream({cancel(){cancels++;return hangs?new Promise<void>(()=>{}):Promise.reject(Error('private-cancel'));}}));response.json=async()=>{reads++;throw Error('No body read');};
    const client=factory(data,async(input,init)=>{if(new URL(String(input)).pathname.endsWith('/login'))return Response.json(tokens('B'));signal=init?.signal;ready.resolve();return held.promise;});
    const user=client.auth.getUser();await ready.promise;await client.auth.signInWithPassword(credentials);const before=data.get('owned');held.resolve(response);expect((await user).error?.name).toBe('AuthStaleOperationError');expect(cancels).toBe(1);expect(signal?.aborted).toBe(true);expect(reads).toBe(0);expect(data.get('owned')).toBe(before);expect((await client.auth.getSession()).data.session?.refresh_token).toBe('refresh-B');
  }
});
