import { it, expect } from 'vitest';
import { randomUUID } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { DatabaseSync } from 'node:sqlite';
import { ownedUserArguments, mutateOwnedNativeUser, databaseDigest } from '../phase-a/native-owned-user.mjs';
it('L1-17 fixture native argv accepts only exact generated owner/email and two targeted verbs, no shell or privileged identity creation',()=>{
  const owner={id:randomUUID(),email:`sdk-live-${randomUUID()}@example.test`},email=`sdk-live-changed-${randomUUID()}@example.test`;
  expect(ownedUserArguments('/owned/traildepot',owner,'change-email',email)).toEqual(['--depot','/owned/traildepot','user','change-email',owner.id,email]);expect(ownedUserArguments('/owned/traildepot',owner,'delete')).toEqual(['--depot','/owned/traildepot','user','delete',owner.id]);
  for(const verb of ['add','mint','admin','invalidate-session','run','delete;DROP'])expect(()=>ownedUserArguments('/owned',owner,verb)).toThrow();
  for(const value of ['--admin','malformed','../../other','email@example.test'])expect(()=>ownedUserArguments('/owned',{...owner,id:value},'delete')).toThrow();
  for(const value of ['not-email','ordinary@example.test','sdk-live-x@example.test','--flag'])expect(()=>ownedUserArguments('/owned',owner,'change-email',value)).toThrow();expect(()=>ownedUserArguments('/owned',owner,'delete',email)).toThrow();
});
it('L1-17 fixture helper refuses nonowned paths before database or native execution',async()=>{
  for(const directory of ['/tmp/live','/Users/unrelated','./.runtime/runs/../other'])await expect(mutateOwnedNativeUser({directory},null,null,{id:randomUUID(),email:`sdk-live-${randomUUID()}@example.test`},'delete')).rejects.toThrow('Refusing non-fixture directory');
});
it('L1-17 missing native UDF root reproduced without weakening checks; repaired main path is readonly and official CLI only',async()=>{
  const db=new DatabaseSync(':memory:');try{expect(()=>db.exec('CREATE TABLE _user(id BLOB,email TEXT CHECK(is_email(email)))')).toThrow(/unknown function|no such function/);expect(()=>db.exec('CREATE TABLE audit(id BLOB CHECK(is_uuid_v4(id)))')).toThrow(/unknown function|no such function/);}finally{db.close();}
  const source=await readFile('tests/phase-a/sdk-auth.test.ts','utf8');expect(source).toContain("'traildepot/data/main.db'), {readOnly:true}");expect(source).not.toMatch(/main\.prepare\(['"](?:UPDATE|DELETE|INSERT)/);const helper=await readFile('tests/phase-a/native-owned-user.mjs','utf8');expect(helper).not.toMatch(/\.function\(|ignore_check_constraints|writable_schema|installTrail\(/);expect(helper).toContain('verifyChecksum');expect(helper).toContain('sqlite_schema ORDER BY type,name');
});
it('L1-17 unrelated sentinel digest detects mutation without exposing identity/session values, refuses caller SQL',()=>{
  const db=new DatabaseSync(':memory:');try{db.exec('CREATE TABLE _user(id BLOB,email TEXT);CREATE TABLE _session(user BLOB,refresh_token TEXT)');const owner=Buffer.alloc(16,1),other=Buffer.alloc(16,2);db.prepare('INSERT INTO _user VALUES(?,?)').run(owner,'owned');db.prepare('INSERT INTO _user VALUES(?,?)').run(other,'sentinel');db.prepare('INSERT INTO _session VALUES(?,?)').run(other,'private-token');const before=databaseDigest(db,'_user','id',owner),session=databaseDigest(db,'_session','user',owner);db.prepare('UPDATE _user SET email=? WHERE id=?').run('changed',owner);expect(databaseDigest(db,'_user','id',owner)).toBe(before);db.prepare('UPDATE _user SET email=? WHERE id=?').run('changed',other);expect(databaseDigest(db,'_user','id',owner)).not.toBe(before);expect(session).not.toContain('private-token');expect(()=>databaseDigest(db,'_user;DROP','id',owner)).toThrow();}finally{db.close();}
});
it('L1-17 diagnostic categories expose booleans only for all16 changes and cleanup permits only captured original/new emails',async()=>{
  const helpers=await import('../phase-a/native-owned-user.mjs'),keys=['schema','config','unrelatedIdentities','unrelatedSessions'];
  for(let mask=0;mask<16;mask++){const before=Object.fromEntries(keys.map(k=>[k,k==='schema'?[{type:'table',name:'owned',tbl_name:'owned',sql:'private-original'}]:'private-original'])),after=Object.fromEntries(keys.map((k,i)=>[k,mask&(1<<i)?k==='schema'?[{type:'table',name:'owned',tbl_name:'owned',sql:'private-mutated'}]:'private-mutated':before[k]]));const changes=helpers.changedNativeState(before,after);expect(Object.keys(changes)).toEqual(['rawSchemaChanged','prohibitedSchemaChange','allowedBookkeepingAdded',...keys.slice(1)]);expect(changes.allowedBookkeepingAdded).toEqual([]);const flags=[changes.prohibitedSchemaChange,changes.config,changes.unrelatedIdentities,changes.unrelatedSessions];for(let i=0;i<4;i++)expect(flags[i]).toBe(Boolean(mask&(1<<i)));expect(JSON.stringify(changes)).not.toContain('private');}
  const owner={id:randomUUID(),email:`sdk-live-${randomUUID()}@example.test`},changed=`sdk-live-changed-${randomUUID()}@example.test`;
  for(const value of [owner.email,changed])expect(helpers.ownedCleanupIdentity(owner,changed,value)).toEqual({id:owner.id,email:value});expect(helpers.ownedCleanupIdentity(owner,changed,undefined)).toBeNull();expect(()=>helpers.ownedCleanupIdentity(owner,changed,`sdk-live-${randomUUID()}@example.test`)).toThrow('unexpected email');expect(()=>helpers.ownedCleanupIdentity({...owner,id:'--other'},changed,owner.email)).toThrow();
});
it('L1-17 private diagnostics retain complete snapshots and successful CLI output in exclusive0600 files, never suppress invariant',async()=>{
  const {mkdtemp,stat,rm}=await import('node:fs/promises'),{tmpdir}=await import('node:os'),{join}=await import('node:path'),helpers=await import('../phase-a/native-owned-user.mjs');const root=await mkdtemp(join(tmpdir(),'native-diagnostic-'));
  try{const payload={before:{config:'private-config',unrelatedSessions:[{refresh_token:'private-refresh'}]},after:{config:'changed'},stdout:'success output',stderr:'success stderr'};const path=await helpers.writeNativeDiagnostic(root,'test','after',payload);expect((await stat(path)).mode&0o777).toBe(0o600);expect(JSON.parse(await readFile(path,'utf8'))).toEqual(payload);await expect(helpers.writeNativeDiagnostic(root,'test','after',payload)).rejects.toThrow();const source=await readFile('tests/phase-a/native-owned-user.mjs','utf8');expect(source).toContain('changed.prohibitedSchemaChange || changed.config || changed.unrelatedIdentities || changed.unrelatedSessions');expect(source).toContain('sqlite_schema ORDER BY type,name');expect(source).toContain("'cli'");expect(source).not.toMatch(/ignore_check_constraints|\.function\(/);}finally{await rm(root,{recursive:true,force:true});}
});
